import type { Metadata } from "next";
import { Amiri } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Footer from "./_Components/Footer/Footer";

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "DR Wafaa Kamel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ direction: "rtl" }}>
      <body className={amiri.className}>
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
